### PR TITLE
Check values schema on push, not only for PRs

### PR DESCRIPTION
**Pull request by AndiDog**
https://github.com/giantswarm/roadmap/issues/2144

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Comment by AndiDog** [comment]
Need to change this again because `GITHUB_BASE_REF` is only available in PRs, not on push. Tested this with `cluster-aws`.

Can @giantswarm/team-rainbow take a look?

**Review by mogottsch — COMMENTED** [review]
The workflow file you modified only checks whether `values.yaml` is a valid payload of the JSON schema defined in `values.schema.json`. 
The error message you posted in slack (`values.yaml is out of sync with values.schema.json...`), is from [this workflow](https://github.com/giantswarm/devctl/blob/main/pkg/gen/input/workflows/internal/file/cluster_app_schema_validation.yaml.template).
I think it makes sense to run that on push as well.

**Comment by AndiDog** [comment]
@mogottsch great idea – I implemented and tested that successfully

**Comment by marians** [comment]
FYI This action does not check whether `values.schema.json` exists

**Pull request merged**
