### PR TITLE
OSSF Scorecard: Update CodeQL action.

### PR DESCRIPTION
**Pull request by Gacko**
We are currently receiving Dependabot PRs for this in repositories managed by `giantswarm/github`. This PR aligns the managed configuration to the actual one.

### CODE REVIEW

**Comment by marians** [comment]
@Gacko In that case, we should configure our presets so that Renovate ignores generated files. Can you please point me to a Renovate PR?

**Comment by Gacko** [comment]
Sure, this one: https://github.com/giantswarm/cluster-autoscaler-app/pull/254#pullrequestreview-1887777606

**Comment by Gacko** [comment]
But this PR here in particular is ok so far?

**Comment by marians** [comment]
> But this PR here in particular is ok so far?

I can't tell, to be honest. That's why I have requested Team Shield to review.

**Comment by Gacko** [comment]
> That was dependabot, not Renovate

Yeah, sorry, my fault. Again. Turns out you were right, I mixed that up because there were so many PRs this morning, some from Renovate but bumping something else, some from Dependabot bumping generated files.

So to get that clear: This dependency in particular got bumped only by Dependabot and we can in fact remove it (Dependabot) from those repositories. Will care for that later.

**Pull request merged**
