### PR TITLE
Accept Path and Automatic Target Names in Makefile

### PR DESCRIPTION
**Pull request by lyind**
## Summary

Make can handle pattern targets and targets which contain path separators.

Those can't currently be documented via the builtin `help` target.

This PR supports `/`, `\` and `%` in the `help` target's name pattern.

## Note

Successfully tested with [Makefile.main.mk](https://github.com/giantswarm/gapps-automation/blob/d3ce77c16e99c190031c1ffc7c9cc7721ea5d686/Makefile.main.mk).

Before merging, maybe test with a really complex project, call `make help` and look if the output matches the expectations.

What's a project with a really complex `Makefile.*.mk`?

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by MarcelMue** [comment]
Not very complex but check if it works with: https://github.com/giantswarm/cluster-api-provider-azure-app/

**Comment by marians** [comment]
@lyind Not sure what I can do for you here. To be honest I don't understand what this PR is doing.

**Comment by lyind** [comment]
### Test with project `cluster-api-provider-azure-app`

Without PR applied:
```
cluster-api-provider-azure-app$ make help

Usage:
  make <target>

General
  help                  Display this help.

App
  lint-chart            Runs ct against the default chart.
  update-chart          Sync chart with upstream repo.
  update-deps           Update Helm dependencies.
  helm-docs             Update $(APPLICATION) README.
```

With PR applied:
```
cluster-api-provider-azure-app$ make help

Usage:
  make <target>

General
  help                  Display this help.

App
  lint-chart            Runs ct against the default chart.
  update-chart          Sync chart with upstream repo.
  update-deps           Update Helm dependencies.
  helm-docs             Update $(APPLICATION) README.
```

**Result:** Same (correct).

**Comment by lyind** [comment]
@marians I clarified the description above.

*Pattern targets* are described here: https://www.gnu.org/software/make/manual/html_node/Pattern_002dspecific.html

(It's a standard feature of make.)

**Pull request merged**
